#Database properties:
db.system: dameng
db.driver: dm.jdbc.driver.DmDriver

instances:
  - db.address: 9.46.118.22
    db.port: 5236
    db.username: SYSDBA
    db.password: VXMzcnBhODgq
    db.connection.url: jdbc:dm://9.46.118.22:5236
    db.name: myDB1

    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    #otel.backend.url: http://9.112.252.66:4317
    otel.backend.url: http://127.0.0.1:4317

    #OTel properties:
    otel.service.name: DamengDC1

  - db.address: 9.46.118.22
    db.port: 5236
    db.username: SYSDBA
    db.password: VXMzcnBhODgq
    db.connection.url: jdbc:dm://9.46.118.22:5236
    db.name: myDB2

    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    #otel.backend.url: http://9.112.252.66:4317
    otel.backend.url: http://127.0.0.1:4317

    #OTel properties:
    otel.service.name: DamengDC2

informix:
  system.info:
    db.system: informix
    db.driver: com.informix.jdbc.IfxDriver
    poll.interval: 10
    callback.interval: 20
    #otel.backend.url:
    otel.backend.url: http://127.0.0.1:4317
    #OTel properties:
    otel.service.name: InformixDB
  instances:
    - db.host: 9.46.251.113
      db.port: 9088
      db.serverName: ol_informix1410
      db.user: informix
      db.password: cGFzc3dvcmQ=
      db.name: TestInformixDB
      #db.user: root
      #db.password: Happy@fyre@neha2021  -   SGFwcHlAZnlyZUBuZWhhMjAyMQ==